services:
  web_alvarezplacas:
    build: .
    container_name: alvarezplacas_web
    restart: always
    ports:
      - "4325:80"
    networks:
      - alvarez_internal
      - javiermix_network
    volumes:
      - ./archivos_alvarezplacas:/usr/share/nginx/html/images/catalog
    environment:
      - DATABASE_URL=postgresql://alvarez_admin:AlvarezAdmin2026@db:5432/alvarezplacas
      - NODE_ENV=production

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: alvarezplacas_files
    restart: always
    ports:
      - "4326:80"
    volumes:
      - ./archivos_alvarezplacas:/srv
      - ./filebrowser.db:/database.db
    networks:
      - alvarez_internal
      - javiermix_network

  db:
    image: postgres:15
    container_name: alvarezplacas_db
    restart: always
    environment:
      - POSTGRES_USER=alvarez_admin
      - POSTGRES_PASSWORD=AlvarezAdmin2026
      - POSTGRES_DB=alvarezplacas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/db-schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - alvarez_internal
      - javiermix_network

networks:
  alvarez_internal:
    driver: bridge
  javiermix_network:
    external: true

volumes:
  postgres_data:
