services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: alvarezplacas.com.ar
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/nginx-proxy-manager/data/custom_ssl/npm-8/fullchain.pem:/etc/letsencrypt/live/alvarezplacas.com.ar/fullchain.pem:ro
      - /home/ubuntu/nginx-proxy-manager/data/custom_ssl/npm-8/privkey.pem:/etc/letsencrypt/live/alvarezplacas.com.ar/privkey.pem:ro
    restart: always
    stop_grace_period: 1m
    networks:
      - default

  snappymail:
    image: ghcr.io/the-djmaze/snappymail:latest
    container_name: snappymail
    restart: always
    environment:
      - SNAPPYMAIL_ADMIN_USER=admin
      - SNAPPYMAIL_ADMIN_PASSWORD=12345
    ports:
      - "8080:8888"
    volumes:
      - ./snappymail-data:/var/lib/snappymail
    depends_on:
      - mailserver
    networks:
      - default
      - javiermix_network

volumes:

networks:
  default:
  javiermix_network:
    external: true
